# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Donnell Muse
title: Donnell Muse | Software Engineer
description: #>-  this means to ignore newlines until "baseurl:"
  my SWE interview cheapsheat

url: https://donnell794.github.io #base hostname & protocol
baseurl: "/interview-study-guide" #subpath for site

location: Berkeley, CA
resume: https://www.dropbox.com/s/nhehdcv091o3iu4/Donnell%20Muse_Resume.pdf?dl=0
social:
  - title: email
    url: mailto:donnellnmuse@gmail.com
  - title: github
    url: https://github.com/donnell794
  - title: linkedin
    url: https://www.linkedin.com/in/donnellmuse

baseurl: "" # the subpath of your site, e.g. /blog
github_username:  donnell794

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
